LansoleProjectBundle:
    resource: "@LansoleProjectBundle/Resources/config/routing.yml"
    prefix:   /

LansoleBlogBundle:
    resource: "@LansoleBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
